global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "shq_connector"
    static_configs:
      - targets: ["shq_connector-web:9394"]
    metrics_path: /metrics

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node_exporter"
    static_configs:
      - targets: ["shq_connector-node-exporter:9100"]
